//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metro.Dialogs.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Metro.Dialogs.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutBoxView_Header_about {
            get {
                return ResourceManager.GetString("AboutBoxView_Header_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string AboutBoxView_Version_LabelText {
            get {
                return ResourceManager.GetString("AboutBoxView_Version_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string DialogServiceExtentios_CancelButtonText_Cancel {
            get {
                return ResourceManager.GetString("DialogServiceExtentios_CancelButtonText_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string DialogServiceExtentios_ExceptionDialogText_Additional {
            get {
                return ResourceManager.GetString("DialogServiceExtentios_ExceptionDialogText_Additional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string DialogServiceExtentios_NoButtonText_No {
            get {
                return ResourceManager.GetString("DialogServiceExtentios_NoButtonText_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string DialogServiceExtentios_OkButtonText_Ok {
            get {
                return ResourceManager.GetString("DialogServiceExtentios_OkButtonText_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string DialogServiceExtentios_YesButtonText_Yes {
            get {
                return ResourceManager.GetString("DialogServiceExtentios_YesButtonText_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved.
        /// </summary>
        public static string WindowsDialogs_AllRightsReserved_All_rights_reserved {
            get {
                return ResourceManager.GetString("WindowsDialogs_AllRightsReserved_All_rights_reserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter....
        /// </summary>
        public static string WindowsDialogs_FilterLabel_Filter {
            get {
                return ResourceManager.GetString("WindowsDialogs_FilterLabel_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string WindowsDialogs_LoginButtonText_Enter {
            get {
                return ResourceManager.GetString("WindowsDialogs_LoginButtonText_Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string WindowsDialogs_LoginDialogPasswordLabel_Password {
            get {
                return ResourceManager.GetString("WindowsDialogs_LoginDialogPasswordLabel_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string WindowsDialogs_LoginDialogTitle_Register {
            get {
                return ResourceManager.GetString("WindowsDialogs_LoginDialogTitle_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string WindowsDialogs_LoginDialogUserNameLabel_Login {
            get {
                return ResourceManager.GetString("WindowsDialogs_LoginDialogUserNameLabel_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string WindowsDialogs_SelectButtonText_Select {
            get {
                return ResourceManager.GetString("WindowsDialogs_SelectButtonText_Select", resourceCulture);
            }
        }
    }
}
